import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {user.isSignedIn ?
          <SignOutButton><span className="text-white p-3 cursor-pointer rounded-md border-white border-2 transition ease-in-out bg-indigo-900 delay-100 hover:scale-110 hover:bg-blue-800 duration-300">Sign Out</span></SignOutButton> :
          <SignInButton><span className="text-white p-3 cursor-pointer rounded-md border-white border-2 transition ease-in-out bg-indigo-900 delay-100 hover:scale-110 hover:bg-blue-800 duration-300">Sign In</span></SignInButton>
        }
        
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
